### ISSUE TITLE
Tree parse error: unexpected token '_os_78_oe_ropschr02g03077' -- not recognized as a sequence name

### ISSUE THREAD

**Issue by erya-song** [smirarab/pasta#68]
Hi,
I'm running PASTA thus:
`run_pasta.py --aligner=mafft --merger=muscle --tree-estimator=fasttree --num-cpus=4 --datatype=protein -i pep/og00090.pep -o 1pasta/og00090`
and getting this erro:
`PASTA failed because one of the programs it tried to run failed.
The invocation that failed was:
    "/home/erya/pasta-code/pasta-master/bin/fasttreeMP" "-quiet" "-wag" "-gamma" "-fastest" "-intree" "/home/erya/.pasta/pastajob/temppkep09an/step0/mincluster/tempfasttreexgyz2k51/start.tre" "-log" "/home/erya/.pasta/pastajob/temppkep09an/step0/mincluster/tempfasttreexgyz2k51/log" "/home/erya/.pasta/pastajob/temppkep09an/step0/mincluster/tempfasttreexgyz2k51/input.fasta"

Ignored unknown character X (seen 130 times)
Tree parse error: unexpected token '_os_78_oe_ropschr02g03077' -- not recognized as a sequence name

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/erya/pasta-code/pasta-master/pasta/scheduler.py", line 195, in __call__
    raise Exception("Job:\n %s\n failed with error code: %d" %(' '.join(plj._invocation), job.return_code))
Exception: Job:
 /home/erya/pasta-code/pasta-master/bin/fasttreeMP -quiet -wag -gamma -fastest -intree /home/erya/.pasta/pastajob/temppkep09an/step0/mincluster/tempfasttreexgyz2k51/start.tre -log /home/erya/.pasta/pastajob/temppkep09an/step0/mincluster/tempfasttreexgyz2k51/log /home/erya/.pasta/pastajob/temppkep09an/step0/mincluster/tempfasttreexgyz2k51/input.fasta
 failed with error code: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erya/miniconda3/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/erya/miniconda3/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/erya/pasta-code/pasta-master/pasta/scheduler.py", line 209, in __call__
    traceback.print_exc(file=err)
  File "/home/erya/miniconda3/lib/python3.9/traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/home/erya/miniconda3/lib/python3.9/traceback.py", line 105, in print_exception
    print(line, file=file, end="")
TypeError: a bytes-like object is required, not 'str'`
How can I deal with it?

**Comment by smirarab** [comment]
My best guess is that your sequences have `_` as the first character of the name and PASTA is not working well with that. But I am not sure. Can you share with me an alignment that includes `_os_78_oe_ropschr02g03077` and 5 other sequences so that I can test?
