### ISSUE TITLE
The alignment file has no sequences. PASTA quits.

### ISSUE THREAD

**Issue by TanHoa-DinhNguyen** [smirarab/pasta#69]
Hi,

I have a trouble when I'm running test `run_pasta.py -i small.fasta`

/usr/local/bin/run_pasta.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('PASTA==1.9.1')
PASTA INFO: Reading input sequences from 'small.fasta'...
PASTA INFO: Masking alignment sites with less than 1 sites before running the tree step
PASTA INFO: Configuration written to "/home/tanhoa96/27ENA/pastajob_temp_pasta_config.txt".

PASTA INFO: Directory for temporary files created at /home/tanhoa96/.pasta/pastajob/tempp4r97pad
PASTA INFO: Name translation information saved to /home/tanhoa96/27ENA/pastajob_temp_name_translation.txt as safe name, original name, blank line format.
PASTA INFO: Creating a starting tree for the PASTA algorithm...
PASTA INFO: Performing initial alignment of the entire data matrix...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/tanhoa96/pasta_code/pasta/pasta/scheduler.py", line 199, in __call__
    job.results = job.result_processor()
  File "/home/tanhoa96/pasta_code/pasta/pasta/tools.py", line 280, in <lambda>
    rpc = lambda : read_internal_alignment(alignedfn,
  File "/home/tanhoa96/pasta_code/pasta/pasta/tools.py", line 79, in read_internal_alignment
    raise ValueError("The alignment file %s has no sequences. PASTA quits." % fn)
ValueError: The alignment file /home/tanhoa96/.pasta/pastajob/tempp4r97pad/init_aln/tempmafftsm0mas61/input.aligned has no sequences. PASTA quits.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tanhoa96/pasta_code/pasta/pasta/scheduler.py", line 211, in __call__
    traceback.print_exc(file=err)
  File "/usr/lib/python3.10/traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/lib/python3.10/traceback.py", line 121, in print_exception
    print(line, file=file, end="")
TypeError: a bytes-like object is required, not 'str'

Any idea on how this can be fixed?

Any help would be appreciated. Thank you very much!

**Comment by xinyu-g** [comment]
Hi  @TanHoa-DinhNguyen , I know this was quite a while ago, but were you able to resolve this problem?

**Comment by smirarab** [comment]
Was PASTA installed using conda?

**Comment by smirarab** [comment]
If pasta was installed suing conda, please update to the lastest version and let me know if the issue is fixed.

**Comment by taoqxtaozi** [comment]
I got the same problem, no output in the .fa.aln file, while I'm using roadies, pasta version is v1.9.3, installed following the instruction on roadies github

**Comment by kristina28** [comment]
I'm having the same problem with v1.9.3. Has anyone resolved it yet?
